# Generated by Django 4.0.1 on 2022-01-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_plane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plane',
            old_name='callsign',
            new_name='icao24',
        ),
    ]
