# Generated by Django 4.0.1 on 2022-01-20 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_rename_callsign_plane_icao24'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='plane',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sighting',
            name='icao24',
            field=models.CharField(default=123, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plane',
            name='passengers',
            field=models.ManyToManyField(to='main_app.Passenger'),
        ),
    ]
